# The URL the site will be built for
base_url = "https://eindex.me"


description = ""
default_language = "en"

build_search_index = false
compile_sass = false

minify_html = false
generate_feed = true
generate_rss = true
feed_filename = "feed.xml"
hard_link_static = false


# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
# skip_prefixes = [
#     "@/posts",
#     "content/posts",
# ]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting
external_links_no_follow = true
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# The theme to use for code highlighting.
highlight_theme = "monokai"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true


[languages]

[languages.cn]
generate_feed = true
title = "EINDEX's Blog"
taxonomies = [
    {name = "series", feed = true},
    {name = "tags"},
]
[languages.cn.translations]
label_archive = "å½’æ¡£"
label_links = "å‹é“¾"
label_about = "å…³äº"
label_books = "ä¹¦"
label_gallery = "ç›¸å†Œ"
label_wiki = "Wiki"
label_thought = "æƒ³æ³•"
label_backlinks = "åå‘é“¾æ¥"

series_financial-independence= "è´¢åŠ¡è‡ªç”±"
series_blog-enhance-plan = "åšå®¢æ¼”è¿›è®¡åˆ’"
series_markdown-testing = "Markdown æµ‹è¯•"
series_qingzhuo = "ç³»åˆ— Testing"
series_algorithm = "ç®—æ³•"
series_security = "åº”ç”¨å®‰å…¨"

[languages.en]
generate_feed = true
title = "EINDEX's Blog"
taxonomies = [
    {name = "series", feed = true},
    {name = "tags"},
]


[languages.en.translations]
label_archive = "Archive"
label_links = "Links"
label_about = "About"
label_books = "Books"
label_gallery = "Gallery"
label_wiki = "Wiki"
label_thought = "Thought"
label_backlinks = "BackLinks"

series_financial-independence = "Financial Independence"
series_blog-enhance-plan = "Blog Enhance Plan"
series_markdown-testing = "Markdown Testing"
series_qingzhuo = "Series Testing"
series_algorithm = "Algorithm"
series_security = "Cyber Security"

[extra]
# Put all your custom variables here
## ICP infomation China mainland only

twitter_user = '@eindex_li'
bio = "My goal is make happy."

adsense = "ca-pub-1265138627025369"
googleAnalytics = "G-SR36ZS0R52"

[extra.webmentions]
[extra.webmentions.posse]
twitter = ["https://twitter.com/eindex_li"]
mastodon = ["https://mastodon.social/@eindex"]

## extra.menus in navbar
[extra.menu]
[[extra.menu.navbar]]
label = "gallery"
url = "gallery"
[[extra.menu.navbar]]
label = "archive"
url = "archive"


[extra.meilisearch]
hostUrl="https://meili.eindex.me"
indexUid="blog"
# this key just provide search permission on blog index.
apiKey="a39cff5442b90bb926f6408b0b08671eee444599e6d9c44c29bd0adae09a4b86"
version="2.4.1"