# The URL the site will be built for
base_url = "https://eindex.me"


description = ""
default_language = "cn"

minify_html = false
generate_feed = true
feed_filename = "feed.xml"

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "@/posts",
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# The theme to use for code highlighting.
highlight_theme = "monokai"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true


[languages]

[languages.cn]
generate_feed = true
title = "EINDEX's Blog"
taxonomies = [
    {name = "series", feed = true},
    {name = "tags"},
    {name = "categories"},
]
[languages.cn.translations]
label_archive = "å½’æ¡£"
label_links = "å‹é“¾"
label_about = "å…³äº"
label_books = "ä¹¦"
label_gallery = "ç›¸å†Œ"
label_wiki = "Wiki"

[languages.en]
generate_feed = true
title = "EINDEX's Blog"
taxonomies = [
    {name = "series", feed = true},
    {name = "tags"},
    {name = "categories"},
]


[languages.en.translations]
label_archive = "Archive"
label_links = "Links"
label_about = "About"
label_books = "Books"
label_gallery = "Gallery"
label_wiki = "Wiki"

[extra]
# Put all your custom variables here
## ICP infomation China mainland only
# googleTagManager = "GTM-PHCB5V2"
# googleAnalytics = 'G-SR36ZS0R52'
# clarity = 'ao1gr1m9ku'
# adsense = "ca-pub-1265138627025369"
twitter_user = '@eindex_li'

[extra.giscus]
repo = "EINDEX/blog"
repoId = "R_kgDOGWb6Yg"
categoryId = "DIC_kwDOGWb6Ys4CAKn-"


## extra.menus in navbar
[extra.menu]
[[extra.menu.navbar]]
label = "wiki"
url = "https://wiki.eindex.me"
external = true
[[extra.menu.navbar]]
label = "gallery"
url = "gallery/_index"
[[extra.menu.navbar]]
label = "archive"
url = "archive"

