# The URL the site will be built for
base_url = "https://eindex.me"


description = ""
default_language = "cn"

minify_html = false
generate_feed = true
feed_filename = "feed.xml"

# Configuration of the link checker.
[link_checker]
# Skip link checking for external URLs that start with these prefixes
skip_prefixes = [
    "@/posts",
]

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true
# The theme to use for code highlighting.
highlight_theme = "monokai"

# When set to "true", emoji aliases translated to their corresponding
# Unicode emoji equivalent in the rendered Markdown files. (e.g.: :smile: => ğŸ˜„)
render_emoji = true


[languages]

[languages.cn]
title = "EINDEX's Blog"
taxonomies = [
    {name = "series", feed = true},
    {name = "tags"},
    {name = "categories"},
]
[languages.cn.translations]


label_archive = "å½’æ¡£"
label_links = "å‹é“¾"
label_about = "å…³äº"

[languages.en]
title = "EINDEX's Blog"
taxonomies = [
    {name = "series", feed = true},
    {name = "tags"},
    {name = "categories"},
]


[languages.en.translations]
label_archive = "Archive"
label_links = "Links"
label_about = "About"

[extra]
# Put all your custom variables here
## ICP infomation China mainland only
clarity = 'ao1gr1m9ku'
adsense = "ca-pub-1265138627025369"

outdateingWarningDays = 60
twitter_user = '@eindex_li'

[extra.giscus]
repo = "EINDEX/blog"
repoId = "R_kgDOGWb6Yg"
categoryId = "DIC_kwDOGWb6Ys4CAKn-"


## extra.menus in navbar
[extra.menu]
[[extra.menu.navbar]]
label = "archive"
name = "å½’æ¡£"
[[extra.menu.navbar]]
label = "links"
name = "å‹é“¾"
cn_only = true
[[extra.menu.navbar]]
label = "about"
name = "å…³äº"





[[extra.socialaccount]]
link = 'https://github.com/eindex'
icon = 'fab fa-github'
label = 'Github'
[[extra.socialaccount]]
link = 'https://twitter.com/eindex_li'
icon = 'fab fa-twitter'
label = 'Twitter'
[[extra.socialaccount]]
link = 'https://t.me/eindex'
icon = 'fab fa-telegram'
label = 'Telegram'
[[extra.socialaccount]]
link = 'mailto:eindex.me@outlook.com'
icon = 'fas fa-envelope'
label = 'Email'


